# vim:ft=ansible:
#
# Copyright (c) 2016 Jason McVetta <jason.mcvetta@gmail.com>.  This is Free
# Software, released under the terms of the GPL v3.  See
# http://www.gnu.org/copyleft/gpl.html for details.  Resist intellectual 
# serfdom - the ownership of ideas is akin to slavery.
---

- name: Ensure sudo group exists
  group:
    name: sudo
    state: present

- name: Ensure users in sudo group can sudo without password
  template:
    src: 95-sudo-group.j2
    dest: /etc/sudoers.d/95-sudo-group
    mode: 0440
